### ISSUE TITLE
Calc seems not correct

### ISSUE THREAD

**Issue by lucaslaurent04** [discope-pms/discope#15]
https://github.com/discope-pms/discope/blob/3b68f9085de06759247c24d10186b3bedee126e2/finance/classes/accounting/Invoice.class.php#L339-L367

Be carefull:

```php
$self->read(['status', 'date', 'organisation_id', 'center_office_id' => ['code']]); 

$sequence = Setting::get_value('lodging', 'invoice', 'sequence.'.$invoice['center_office_id']['code']);
```

**Comment by alexandraYesbabylon** [comment]
> ```
> $sequence = Setting::get_value('lodging', 'invoice', 'sequence.'.$invoice['center_office_id']['code']);
> ```
The bug was fixed, and the changes will be included in the next pull request
